### ISSUE TITLE
Add IP pool

### ISSUE THREAD

**Issue by edwardtheharris** [edwardtheharris/helm-networking#6]
```yaml
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: example.ippool
spec:
  cidr: 10.1.0.0/16
  ipipMode: CrossSubnet
  natOutgoing: true
  disabled: false
  nodeSelector: all()
  allowedUses:
    - Workload
    - Tunnel
```
